name = "ncio"
version = "0.1.0"
license = "license"
author = "alex-robinson"
maintainer = ""
copyright = "Copyright 2013, alex-robinson"
[build]
auto-executables = true
auto-tests = false
auto-examples = true
external-modules = ["netcdff","netcdf"]
link = ["netcdff","netcdf"]
[install]
library = false
[[test]]
name = "test_ncio"

